apiVersion: v1
kind: Service
metadata:
  name: {{ include "docker-node-init.fullname" . }}
  labels:
    {{- include "docker-node-init.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}
      protocol: TCP
      name: http
  selector:
    {{- include "docker-node-init.selectorLabels" . | nindent 4 }}
  externalTrafficPolicy: {{ .Values.service.externalTrafficPolicy }}